Task.create(task_name: "Move with Lil to the black mountain hills of Dakota", completed: false)
Task.create(task_name: "Lose Lil to Danny", completed: true)
Task.create(task_name: "Get hit in the eye by Danny", completed: false)
Task.create(task_name: "Walk into town seeking revenge", completed: false)
Task.create(task_name: "Book room at local saloon", completed: false)
Task.create(task_name: "Check into room and read Gideon's bible", completed: false)
Task.create(task_name: "Drink too much gin", completed: false)
Task.create(task_name: "Overhear Lil and Danny in neighboring room", completed: false)
Task.create(task_name: "Burst into neighboring room and declare a showdown", completed: false)
Task.create(task_name: "Get shot by Danny and collapse in corner", completed: false)
Task.create(task_name: "Visit doctor", completed: false)
Task.create(task_name: "Return to room and read Gideon's bible", completed: false)
Task.create(task_name: "Sing along! D'do d'do d'do do do d'do d'do d'do", completed: false)
Task.create(task_name: "Get Pizza", completed: false)

Tag.create(tag_name: "Death")
Tag.create(tag_name: "Amazing")
Tag.create(tag_name: "Urgent")
Tag.create(tag_name: "Cha Cha Cha Cha Changing AKA David Bowie Lyrics")

TaskTag.create(task_id: 10,tag_id: 1)
TaskTag.create(task_id: 14,tag_id: 1)
TaskTag.create(task_id: 7,tag_id: 3)
TaskTag.create(task_id: 11,tag_id: 3)
TaskTag.create(task_id: 14,tag_id: 3)
TaskTag.create(task_id: 7,tag_id: 2)
TaskTag.create(task_id: 13,tag_id: 2)
TaskTag.create(task_id: 6,tag_id: 2)
TaskTag.create(task_id: 13,tag_id: 4)
TaskTag.create(task_id: 5,tag_id: 4)
